[package]
name = "aether-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Aether 字节码 VM(M5)"

[dependencies]
aether-ast = { path = "../aether-ast" }
aether-diagnostic = { path = "../aether-diagnostic" }
aether-interp = { path = "../aether-interp" }

[dev-dependencies]
aether-parser = { path = "../aether-parser" }
aether-verify = { path = "../aether-verify" }
